### ISSUE TITLE
Allow volumes to be shared across components

### ISSUE THREAD

**Issue by johnmcollier** [che-incubator/devworkspace-api#16]
Odo will have a need for multiple components to mount the same volume. There isn’t an option in devfiles right now to define a volume once, and have multiple components mount that same volume. 

To work around this, we’re proposing adding a way to the devfile spec that allows you to define a volume once (a top level ‘volumes’ field), then easily add it to other components via a ‘volumeMount’ field. Like how Kubernetes handles volumes in containers, there'd be a top level `volumes` field and a `volumeMounts` field in the component:

```
projects:
  - name: "my-project"
volumes: 
  - name: my-data-volume
    size: 5Gi
components:
  - container:
      image: "busybox"
      name: "mycontainer"
      memoryLimit: "128M"
      mountSources: true
      volumeMount:
        - name: my-data-volume
          path: /some/folder
  - container:
      image: "busybox"
      name: "mycontainer"
      memoryLimit: "128M"
      mountSources: true
      volumeMount:
        - name: my-data-volume
          path: /some/other/folder
```
