### ISSUE TITLE
Terminating components

### ISSUE THREAD

**Issue by l0rd** [che-incubator/devworkspace-api#37]
```yaml
---
components:
  - container:
        image: maven
        terminating: true
  - kubernetes:
       reference: https://.../mongo.yaml
       terminating: true
  - plugin:
        id: java         # <-- terminating is not supported for plugins components (terminating=true/false can be specified in the plugin definition)
```
