### ISSUE TITLE
Specify the development lifecycle step of a command

### ISSUE THREAD

**Issue by l0rd** [che-incubator/devworkspace-api#6]
We need to agree on a convention to specify the step(s) of the development lifecycle a command belongs to.  For example a given command will be used during the `build` step and another one is used for the `run` step. Tools like `odo` and `che` will then leverage this information to infer the sequence of the commands that need to be run.

A possible convention we can agree on is to specify the `lifecycleStep` as command annotation:

```yaml
commands:
  - exec:
      annotations:
        lifecycleStep: build
      commandLine: "./build.sh"
      component: build-container
  - exec:
      annotations:
        lifecycleStep: run
      commandLine: "./run.sh"
      component: runtime-container
```
